# wrangler.toml (for Cloudflare Pages with .next output)
name = "evans-website"
compatibility_date = "2025-10-23"

# Tell wrangler which folder to upload for Pages
pages_build_output_dir = ".next"

# Optional: env vars for wrangler *local* runs (prefer the Dashboard for real deploys)
[vars]
NODE_ENV = "production"